CREATE TABLE IF NOT EXISTS Users(
UserId  SERIAL PRIMARY KEY,
UserName VARCHAR(50) NOT NULL,
Address VARCHAR(50) NOT NULL,
PhoneNumber VARCHAR(20) NOT NULL,
Email VARCHAR(255) NOT NULL,
Password VARCHAR(255) NOT NULL,
EmailVerified BOOLEAN DEFAULT False,
)


