CREATE TABLE IF NOT EXISTS Customers(
CustomerId  SERIAL PRIMARY KEY,
CustomerName VARCHAR(50) NOT NULL,
ContactName VARCHAR(50),
Address VARCHAR(50) NOT NULL,
City VARCHAR(50)NOT NULL,
PostalCode VARCHAR(50),
Country VARCHAR(50)NOT NULL
)
