CREATE TABLE IF NOT EXISTS Employees(
EmployeeId SERIAL PRIMARY KEY,
LastName VARCHAR(50) NOT NULL,
FirstName VARCHAR(50) NOT NULL,
BirthDate DATE NOT NULL,
Photo VARCHAR(100) NOT NULL,
Notes VARCHAR(555) 
)
