# Use an appropriate base image (e.g., Node.js)
FROM node:18-alpine
# Set the working directory inside the container
WORKDIR /app
# Copy package.json and package-lock.json to the working directory
COPY package.json .
COPY package-lock.json .
# Install dependencies
RUN npm install
# Copy the rest of the application files
COPY . .
# Build the TypeScript code
RUN npm run build
# Expose the port your application runs on (if necessary)
EXPOSE 3005
# Specify the command to start the applicationS
CMD ["npm", "run", "dev"]
