export const ACCESS_TOKEN_EXPIRY = 600000;
export const REFRESH_TOKEN_EXPIRY = 6000000;
// export const ACCESS_TOKEN_SECRET = "ACCESS_TOKEN_SECRET";
// export const REFRESH_TOKEN_SECRET = "REFRESH_TOKEN_SECRET";
